# site settings
title: DEVREAL
header_title: DEVREAL Tech Conversations
subtitle: Tech Conversations
email: sven@malvik.de
form-link: https://forms.microsoft.com/Pages/ResponsePage.aspx?id=XcJbgGSO1k6NJDiDyQaMWnRqPntVDDNGvw5-fOu_j7tUMUJaQjZCRzU1VkpIODdYVjlMU0ZZRzdaMC4u
description: "How are Norwegian companies like Vipps, SATS, Orkla, and Statsbygg using Azure API Management? What experiences do they have, and what do they think about the service? "
baseurl: ""
url: 
author: Sven Malvik
street_address: Trett√•sen 50
city: Fjerdingby
state: 
zip_code: 2008
country: Norway
phone: (+47) 948 225 79

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6
reserve_btn: "Reserve Free Seat"

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/svenmalvik
pinterest_url:
slack_url:
twitter_url:

markdown: kramdown

sass:
  style: compressed
